import { db } from '../../db/database'
import type {
  Exercise,
  WorkoutTemplate,
  WorkoutTemplateExercise,
} from '../../types/training'

const now = '2026-08-30T00:00:00.000Z'

function base(id: string) {
  return {
    id,
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
    version: 1,
  }
}

const exercises: Exercise[] = [
  {
    ...base('ex-bench-press'),
    name: 'Press banca',
    primaryMuscle: 'Pecho',
    secondaryMuscles: ['Tríceps', 'Deltoides anteriores'],
    equipment: 'Barra',
    exerciseType: 'compound',
    spineLoad: 'moderate',
    techniqueNotes:
      'Mantén una posición estable y utiliza un rango de movimiento cómodo y controlado.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-incline-dumbbell-press'),
    name: 'Press inclinado con mancuernas',
    primaryMuscle: 'Pecho',
    secondaryMuscles: ['Tríceps', 'Deltoides anteriores'],
    equipment: 'Mancuernas',
    exerciseType: 'compound',
    spineLoad: 'moderate',
    techniqueNotes:
      'Controla la bajada y alcanza una posición suficientemente elongada.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-cable-fly'),
    name: 'Aperturas en polea',
    primaryMuscle: 'Pecho',
    secondaryMuscles: [],
    equipment: 'Polea',
    exerciseType: 'isolation',
    spineLoad: 'low',
    techniqueNotes:
      'Mantén el control y evita acortar innecesariamente la posición de estiramiento.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-pull-up'),
    name: 'Dominadas',
    primaryMuscle: 'Espalda',
    secondaryMuscles: ['Bíceps'],
    equipment: 'Peso corporal',
    exerciseType: 'compound',
    spineLoad: 'low',
    techniqueNotes: 'Utiliza un recorrido amplio y controlado.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-lat-pulldown'),
    name: 'Jalón al pecho',
    primaryMuscle: 'Espalda',
    secondaryMuscles: ['Bíceps'],
    equipment: 'Polea',
    exerciseType: 'compound',
    spineLoad: 'low',
    techniqueNotes:
      'Permite una extensión controlada arriba y dirige los codos hacia abajo.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-chest-supported-row'),
    name: 'Remo con pecho apoyado',
    primaryMuscle: 'Espalda',
    secondaryMuscles: ['Bíceps', 'Deltoides posteriores'],
    equipment: 'Mancuernas',
    exerciseType: 'compound',
    spineLoad: 'low',
    techniqueNotes: 'Mantén el pecho apoyado y controla todo el recorrido.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-chest-supported-tbar-row'),
    name: 'Remo T con pecho apoyado',
    primaryMuscle: 'Espalda',
    secondaryMuscles: ['Bíceps', 'Deltoides posteriores'],
    equipment: 'Máquina / T-Bar',
    exerciseType: 'compound',
    spineLoad: 'low',
    techniqueNotes: 'Mantén el torso apoyado y evita convertirlo en un tirón corporal.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-seated-cable-row'),
    name: 'Remo sentado en polea',
    primaryMuscle: 'Espalda',
    secondaryMuscles: ['Bíceps'],
    equipment: 'Polea',
    exerciseType: 'compound',
    spineLoad: 'low',
    techniqueNotes:
      'Permite una extensión controlada al inicio y rema sin impulso excesivo.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-lateral-raise'),
    name: 'Elevaciones laterales',
    primaryMuscle: 'Hombros',
    secondaryMuscles: [],
    equipment: 'Mancuernas',
    exerciseType: 'isolation',
    spineLoad: 'low',
    techniqueNotes:
      'Eleva de forma controlada. No es necesario mantener el torso completamente inmóvil a cualquier coste.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-face-pull'),
    name: 'Face Pull',
    primaryMuscle: 'Hombros',
    secondaryMuscles: ['Espalda'],
    equipment: 'Polea',
    exerciseType: 'isolation',
    spineLoad: 'low',
    techniqueNotes: 'Controla el movimiento y adapta la trayectoria a una posición cómoda.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-bayesian-curl'),
    name: 'Curl Bayesian en polea',
    primaryMuscle: 'Bíceps',
    secondaryMuscles: [],
    equipment: 'Polea',
    exerciseType: 'isolation',
    spineLoad: 'low',
    techniqueNotes:
      'Coloca el brazo ligeramente detrás del torso y conserva la posición elongada.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-incline-dumbbell-curl'),
    name: 'Curl inclinado con mancuernas',
    primaryMuscle: 'Bíceps',
    secondaryMuscles: [],
    equipment: 'Mancuernas',
    exerciseType: 'isolation',
    spineLoad: 'low',
    techniqueNotes: 'Mantén una posición elongada del bíceps y controla la repetición.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-hammer-curl'),
    name: 'Curl martillo',
    primaryMuscle: 'Bíceps',
    secondaryMuscles: ['Antebrazo'],
    equipment: 'Mancuernas',
    exerciseType: 'isolation',
    spineLoad: 'low',
    techniqueNotes: 'Agarre neutro y repetición controlada.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-ez-bar-curl'),
    name: 'Curl con barra EZ',
    primaryMuscle: 'Bíceps',
    secondaryMuscles: [],
    equipment: 'Barra EZ',
    exerciseType: 'isolation',
    spineLoad: 'low',
    techniqueNotes: 'Utiliza un recorrido cómodo y una excéntrica controlada.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-triceps-pushdown'),
    name: 'Extensión de tríceps en polea',
    primaryMuscle: 'Tríceps',
    secondaryMuscles: [],
    equipment: 'Polea',
    exerciseType: 'isolation',
    spineLoad: 'low',
    techniqueNotes: 'Mantén una ejecución estable y alcanza una extensión cómoda.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-overhead-triceps-extension'),
    name: 'Extensión de tríceps sobre la cabeza',
    primaryMuscle: 'Tríceps',
    secondaryMuscles: [],
    equipment: 'Polea',
    exerciseType: 'isolation',
    spineLoad: 'low',
    techniqueNotes:
      'Busca una posición elongada del tríceps sin forzar hombros o codos.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-hack-squat'),
    name: 'Hack Squat',
    primaryMuscle: 'Cuádriceps',
    secondaryMuscles: ['Glúteos'],
    equipment: 'Máquina',
    exerciseType: 'compound',
    spineLoad: 'moderate',
    techniqueNotes:
      'Desciende hasta un rango cómodo manteniendo una trayectoria estable.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-leg-press'),
    name: 'Prensa de piernas',
    primaryMuscle: 'Cuádriceps',
    secondaryMuscles: ['Glúteos'],
    equipment: 'Máquina',
    exerciseType: 'compound',
    spineLoad: 'moderate',
    techniqueNotes:
      'Utiliza un rango profundo que puedas controlar sin perder una posición estable.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-leg-extension'),
    name: 'Extensión de cuádriceps',
    primaryMuscle: 'Cuádriceps',
    secondaryMuscles: [],
    equipment: 'Máquina',
    exerciseType: 'isolation',
    spineLoad: 'low',
    techniqueNotes: 'Controla ambas fases de la repetición.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-leg-curl'),
    name: 'Curl femoral',
    primaryMuscle: 'Isquiosurales',
    secondaryMuscles: [],
    equipment: 'Máquina',
    exerciseType: 'isolation',
    spineLoad: 'low',
    techniqueNotes:
      'Controla la fase excéntrica y conserva el recorrido disponible.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-rdl'),
    name: 'Peso muerto rumano',
    primaryMuscle: 'Isquiosurales',
    secondaryMuscles: ['Glúteos'],
    equipment: 'Barra',
    exerciseType: 'compound',
    spineLoad: 'high',
    techniqueNotes:
      'Realiza una bisagra de cadera controlada y detén el descenso donde mantengas una posición sólida.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-hip-thrust'),
    name: 'Hip Thrust',
    primaryMuscle: 'Glúteos',
    secondaryMuscles: ['Isquiosurales'],
    equipment: 'Barra',
    exerciseType: 'compound',
    spineLoad: 'low',
    techniqueNotes: 'Extiende la cadera sin buscar hiperextensión lumbar.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-standing-calf-raise'),
    name: 'Elevación de gemelos de pie',
    primaryMuscle: 'Gemelos',
    secondaryMuscles: [],
    equipment: 'Máquina',
    exerciseType: 'isolation',
    spineLoad: 'low',
    techniqueNotes: 'Utiliza un recorrido amplio y controlado.',
    mediaPath: null,
    mediaType: null,
  },
  {
    ...base('ex-seated-calf-raise'),
    name: 'Elevación de gemelos sentado',
    primaryMuscle: 'Gemelos',
    secondaryMuscles: [],
    equipment: 'Máquina',
    exerciseType: 'isolation',
    spineLoad: 'low',
    techniqueNotes: 'Utiliza un recorrido amplio y controlado.',
    mediaPath: null,
    mediaType: null,
  },
]

const workoutTemplates: WorkoutTemplate[] = [
  {
    ...base('workout-upper-a'),
    name: 'Upper A',
    dayOfWeek: 1,
    type: 'upper',
    description: 'Torso con énfasis de empuje.',
  },
  {
    ...base('workout-lower-a'),
    name: 'Lower A',
    dayOfWeek: 2,
    type: 'lower',
    description: 'Pierna con énfasis en cuádriceps.',
  },
  {
    ...base('workout-upper-b'),
    name: 'Upper B',
    dayOfWeek: 4,
    type: 'upper',
    description: 'Torso con énfasis de tirón.',
  },
  {
    ...base('workout-lower-b'),
    name: 'Lower B',
    dayOfWeek: 5,
    type: 'lower',
    description: 'Pierna con énfasis en cadena posterior.',
  },
]

function templateExercise(
  id: string,
  workoutTemplateId: string,
  exerciseId: string,
  order: number,
  targetSets: number,
  minReps: number,
  maxReps: number,
  restSeconds: number,
  referenceWeight: number | null,
): WorkoutTemplateExercise {
  return {
    ...base(id),
    workoutTemplateId,
    exerciseId,
    order,
    targetSets,
    minReps,
    maxReps,
    targetRir: 2,
    restSeconds,
    referenceWeight,
  }
}

const templateExercises: WorkoutTemplateExercise[] = [
  // UPPER A
  templateExercise(
    'uta-1',
    'workout-upper-a',
    'ex-bench-press',
    1,
    3,
    6,
    8,
    180,
    25,
  ),
  templateExercise(
    'uta-2',
    'workout-upper-a',
    'ex-chest-supported-row',
    2,
    3,
    8,
    12,
    120,
    null,
  ),
  templateExercise(
    'uta-3',
    'workout-upper-a',
    'ex-incline-dumbbell-press',
    3,
    3,
    8,
    12,
    120,
    24,
  ),
  templateExercise(
    'uta-4',
    'workout-upper-a',
    'ex-lat-pulldown',
    4,
    3,
    8,
    12,
    120,
    50,
  ),
  templateExercise(
    'uta-5',
    'workout-upper-a',
    'ex-lateral-raise',
    5,
    3,
    12,
    20,
    60,
    5,
  ),
  templateExercise(
    'uta-6',
    'workout-upper-a',
    'ex-bayesian-curl',
    6,
    3,
    8,
    15,
    90,
    8,
  ),
  templateExercise(
    'uta-7',
    'workout-upper-a',
    'ex-triceps-pushdown',
    7,
    3,
    8,
    15,
    90,
    20,
  ),

  // LOWER A
  templateExercise(
    'lta-1',
    'workout-lower-a',
    'ex-hack-squat',
    1,
    4,
    8,
    10,
    180,
    30,
  ),
  templateExercise(
    'lta-2',
    'workout-lower-a',
    'ex-leg-press',
    2,
    3,
    10,
    15,
    120,
    120,
  ),
  templateExercise(
    'lta-3',
    'workout-lower-a',
    'ex-leg-curl',
    3,
    3,
    10,
    15,
    90,
    30,
  ),
  templateExercise(
    'lta-4',
    'workout-lower-a',
    'ex-hip-thrust',
    4,
    3,
    8,
    12,
    120,
    null,
  ),
  templateExercise(
    'lta-5',
    'workout-lower-a',
    'ex-leg-extension',
    5,
    3,
    10,
    15,
    90,
    null,
  ),
  templateExercise(
    'lta-6',
    'workout-lower-a',
    'ex-standing-calf-raise',
    6,
    3,
    10,
    15,
    60,
    null,
  ),

  // UPPER B
  templateExercise(
    'utb-1',
    'workout-upper-b',
    'ex-pull-up',
    1,
    3,
    6,
    10,
    180,
    null,
  ),
  templateExercise(
    'utb-2',
    'workout-upper-b',
    'ex-cable-fly',
    2,
    3,
    10,
    15,
    90,
    25,
  ),
  templateExercise(
    'utb-3',
    'workout-upper-b',
    'ex-chest-supported-tbar-row',
    3,
    3,
    8,
    12,
    120,
    25,
  ),
  templateExercise(
    'utb-4',
    'workout-upper-b',
    'ex-seated-cable-row',
    4,
    3,
    10,
    15,
    90,
    35,
  ),
  templateExercise(
    'utb-5',
    'workout-upper-b',
    'ex-lateral-raise',
    5,
    3,
    12,
    20,
    60,
    5,
  ),
  templateExercise(
    'utb-6',
    'workout-upper-b',
    'ex-hammer-curl',
    6,
    3,
    8,
    15,
    90,
    10,
  ),
  templateExercise(
    'utb-7',
    'workout-upper-b',
    'ex-overhead-triceps-extension',
    7,
    3,
    8,
    15,
    90,
    20,
  ),

  // LOWER B
  templateExercise(
    'ltb-1',
    'workout-lower-b',
    'ex-rdl',
    1,
    3,
    8,
    10,
    120,
    null,
  ),
  templateExercise(
    'ltb-2',
    'workout-lower-b',
    'ex-leg-press',
    2,
    3,
    10,
    15,
    120,
    120,
  ),
  templateExercise(
    'ltb-3',
    'workout-lower-b',
    'ex-leg-curl',
    3,
    4,
    10,
    12,
    90,
    30,
  ),
  templateExercise(
    'ltb-4',
    'workout-lower-b',
    'ex-hip-thrust',
    4,
    3,
    10,
    15,
    90,
    null,
  ),
  templateExercise(
    'ltb-5',
    'workout-lower-b',
    'ex-leg-extension',
    5,
    3,
    12,
    15,
    90,
    null,
  ),
  templateExercise(
    'ltb-6',
    'workout-lower-b',
    'ex-seated-calf-raise',
    6,
    3,
    12,
    20,
    60,
    null,
  ),
]

export async function ensureTrainingSeed() {
  const existingTemplates = await db.workoutTemplates.count()

  if (existingTemplates > 0) {
    return
  }

  await db.transaction(
    'rw',
    db.exercises,
    db.workoutTemplates,
    db.workoutTemplateExercises,
    async () => {
      await db.exercises.bulkPut(exercises)
      await db.workoutTemplates.bulkPut(workoutTemplates)
      await db.workoutTemplateExercises.bulkPut(templateExercises)
    },
  )
}