import { test, expect } from '@playwright/test'
import { openApp, mainNav, segmented, seedGoldenVisualFacts, readStore } from './helpers'
import { populateGoldenActiveSession } from './activeGoldenFixture'
import type { ExerciseSet, WorkoutSession } from '../../../src/types/training'

test('session owner preserves editable sets, explicit removal and rest across navigation', async ({page}) => {
  await page.clock.setFixedTime(new Date('2026-09-03T07:41:00+02:00'))
  await openApp(page)
  await seedGoldenVisualFacts(page,'07')
  await openApp(page)
  await mainNav(page,'Training')
  await segmented(page,'Secciones de Training','Rutinas')
  await page.locator('.training-routine-card').filter({has:page.getByRole('heading',{name:'Upper B',exact:true})}).getByRole('button',{name:'Ver detalle'}).click()
  await page.getByRole('dialog').getByRole('button',{name:'Iniciar rutina'}).click()
  await expect(page.getByText('TRAINING · EN CURSO',{exact:true})).toBeVisible()
  await populateGoldenActiveSession(page)
  await openApp(page)
  await page.getByRole('navigation',{name:'Navegación principal'}).getByRole('button',{name:'Training',exact:true}).click()
  const rows=page.locator('.training-set-row')
  await expect(rows).toHaveCount(5)
  await expect(page.locator('.training-rest-timer strong')).toContainText('01:24')
  await expect(rows.first().getByRole('spinbutton').last()).toBeDisabled()
  const pending=rows.nth(3)
  await pending.getByRole('spinbutton').first().fill('25')
  await pending.getByRole('spinbutton').nth(1).click()
  await expect.poll(async()=> (await readStore<ExerciseSet>(page,'exerciseSets')).find(item=>item.id==='visual-active-working-2')?.weight).toBe(25)
  await pending.getByRole('button',{name:'Completar serie'}).click()
  await expect.poll(async()=> Boolean((await readStore<ExerciseSet>(page,'exerciseSets')).find(item=>item.id==='visual-active-working-2')?.completedAt)).toBe(true)
  await page.getByRole('button',{name:'Saltar descanso'}).click()
  await expect(page.locator('.training-rest-timer')).toHaveCount(0)
  const last=rows.last()
  await last.getByLabel('Opciones de serie 3').click()
  await last.getByRole('button',{name:'Eliminar serie'}).click()
  await expect(rows).toHaveCount(4)
  await page.getByRole('button',{name:'Añadir serie',exact:false}).click()
  await expect(rows).toHaveCount(5)
  const sessions=await readStore<WorkoutSession>(page,'workoutSessions')
  expect(sessions.filter(item=>item.status==='active')).toHaveLength(1)
  await page.getByRole('navigation',{name:'Navegación principal'}).getByRole('button',{name:'Hoy',exact:true}).click()
  await page.getByRole('navigation',{name:'Navegación principal'}).getByRole('button',{name:'Training',exact:true}).click()
  await expect(rows).toHaveCount(5)
  expect((await readStore<ExerciseSet>(page,'exerciseSets')).find(item=>item.id==='visual-active-working-2')?.weight).toBe(25)
})
