"""Build lossless runtime copies, preserving all licensed masters and marks."""
from pathlib import Path
from PIL import Image, ImageChops, ImageStat
import hashlib
import json
import unicodedata

ROOT = Path(__file__).resolve().parents[1]
MASTERS = ROOT / '_incoming/gymvisual_raw'
RUNTIME = ROOT / 'public/media/exercises/user-licensed'
RUNTIME.mkdir(parents=True, exist_ok=True)
MAPPING = {
    'ex-bench-press': 'press banca', 'ex-incline-dumbbell-press': 'Press inclinado mancuernas',
    'ex-cable-fly': 'Aperturas en polea', 'ex-pull-up': 'Dominadas', 'ex-lat-pulldown': 'Jalón al pecho',
    'ex-chest-supported-row': 'Remo mancuernas con apoyo torácico',
    'ex-chest-supported-tbar-row': 'Remo T con pecho apoyado', 'ex-seated-cable-row': 'Remo sentado en polea',
    'ex-lateral-raise': 'Elevación lateral', 'ex-face-pull': 'Face Pull', 'ex-bayesian-curl': 'Curl Bayesian',
    'ex-incline-dumbbell-curl': 'Curl inclinado mancuernas', 'ex-hammer-curl': 'Hammer Curl',
    'ex-ez-bar-curl': 'Curl barra EZ', 'ex-triceps-pushdown': 'Triceps Pushdown',
    'ex-overhead-triceps-extension': 'Extensión tríceps overhead polea', 'ex-hack-squat': 'Hack Squat',
    'ex-leg-press': 'Leg Press', 'ex-leg-extension': 'Leg Extension', 'ex-leg-curl': 'Curl femoral tumbado',
    'ex-hip-thrust': 'Hip Thrust', 'ex-rdl': 'Romanian Deadlift', 'ex-seated-calf-raise': 'Gemelo sentado',
    'ex-standing-calf-raise': 'Gemelo de pie', 'ex-cat-cow': 'Cat Cow', 'ex-open-book': 'Open Book',
    'ex-90-90-hip-switch': '90-90 Hip Switch', 'ex-hip-flexor-stretch': 'Hip Flexor Stretch',
    'ex-wall-slides': 'Wall Slides', 'ex-bird-dog': 'Bird Dog', 'ex-dead-bug': 'Dead Bug',
    'ex-side-plank': 'Side Plank', 'ex-breathing-reset': 'Respiración-movilidad suave',
}
# Names alone cannot override the actual exercise identity depicted in a file.
EXCLUSIONS = {
    'ex-lat-pulldown': 'File depicts standing straight-arm cable pulldown, not the catalog seated elbow-flexion lat pulldown; retain canonical fallback.',
    'ex-chest-supported-tbar-row': 'File depicts unsupported bent-over T-bar row without chest pad; retain original chest-supported FENIX asset.',
}
def normalized(value):
    return ''.join(c for c in unicodedata.normalize('NFD', value.casefold()) if unicodedata.category(c) != 'Mn')
def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()
files = {normalized(p.stem): p for p in MASTERS.glob('*.gif')}
runtime = {}
inventory = []
for exercise_id, title in MAPPING.items():
    master = files.get(normalized(title))
    if master is None:
        inventory.append(dict(exerciseId=exercise_id, status='NO_FILE_KEEP_FALLBACK'))
        continue
    before = sha(master)
    with Image.open(master) as gif:
        size = gif.size
        frames, durations = [], []
        for i in range(gif.n_frames):
            gif.seek(i)
            frames.append(gif.convert('RGBA').copy())
            durations.append(max(20, gif.info.get('duration', 100) or 100))
    poster = RUNTIME / f'{exercise_id}-poster.webp'
    peak = RUNTIME / f'{exercise_id}-peak.webp'
    sprite = RUNTIME / f'{exercise_id}-frames.webp'
    frames[0].save(poster, 'WEBP', lossless=True, method=6)
    peak_frame = max(range(len(frames)), key=lambda i: sum(ImageStat.Stat(ImageChops.difference(frames[0].convert('RGB'), frames[i].convert('RGB'))).sum))
    frames[peak_frame].save(peak, 'WEBP', lossless=True, method=6)
    sheet = Image.new('RGBA', (size[0], size[1]*len(frames)))
    for i, frame in enumerate(frames):
        sheet.paste(frame, (0, i*size[1]))
    sheet.save(sprite, 'WEBP', lossless=True, method=6)
    assert sha(master) == before
    data = dict(poster=f'/media/exercises/user-licensed/{poster.name}',
                peak=f'/media/exercises/user-licensed/{peak.name}',
                sprite=f'/media/exercises/user-licensed/{sprite.name}',
                width=size[0], height=size[1], durations=durations, peakFrame=peak_frame)
    if exercise_id not in EXCLUSIONS:
        runtime[exercise_id] = data
    inventory.append(dict(exerciseId=exercise_id, master=str(master.relative_to(ROOT)),
        masterSHA256=before, match='exact/normalized Spanish title or explicit equivalent alias',
        status='IDENTITY_MISMATCH_KEEP_FALLBACK' if exercise_id in EXCLUSIONS else 'INTEGRATED',
        note=EXCLUSIONS.get(exercise_id, 'Full original frame and watermark retained; no remote runtime URL'),
        frames=len(frames), runtime=data,
        derivedSHA256={p.name: sha(p) for p in [poster, peak, sprite]}))
header = '''// Generated by scripts/integrate-user-media.py; masters remain immutable.
export interface UserMediaDefinition { poster: string; peak: string; sprite: string; width: number; height: number; durations: number[]; peakFrame: number }
export const USER_LICENSED_MEDIA: Readonly<Record<string, UserMediaDefinition>> = '''
(ROOT/'src/features/training/media/userMediaManifest.ts').write_text(header+json.dumps(runtime,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
(ROOT/'qa/v2.1/evidence/USER_MEDIA_MAPPING.json').write_text(json.dumps(inventory,ensure_ascii=False,indent=2),encoding='utf-8')
print(f'{len(inventory)} masters inventoried; {len(runtime)} matching assets selected; originals SHA-256 unchanged.')
